config/routes.rb
Rails.application.routes.draw do
  root to: "welcomes#index"

  get "/apresentacao", to: "welcomes#apresentacao"
  get "/acesso_livre", to: "welcomes#acesso_livre"
  get "/temas", to: "welcomes#temas"
  get "/cursos", to: "welcomes#cursos"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_for :admins, skip: [ :registrations ], path: "admin", controllers: { sessions: "admins/sessions" }, path_names: {
    sign_in: "login",
    sign_out: "logout"
  }

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    get "alunos", to: "alunos#index"
    get "pedidos", to: "pedidos#index"
    get "pagamento", to: "pagamento#index"
    get "correcoes", to: "correcoes#index"
    get "find_by_alunos", to: "correcoes#alunos"
    get "alunos/:id/notifications", to: "alunos#notifications", as: "aluno_notifications"
    get "chats/:id/messages", to: "chats#messages", as: :chat_messages

    resources :correcoes
    resources :temas
    resources :words

    resources :chats, only: [ :show ] do
      resources :messages, only: [ :create ]
    end

    resources :users do
      member do
        patch :toggle_active
      end
    end

    resources :cursos do
      collection do
        post :delete_multiple
        post :add_word
        post :remove_word
      end

      post :destroy_image, on: :member
    end

    post "adicionar_cursos", to: "alunos#adicionar_cursos", as: :adicionar_cursos
    post "adicionar_words", to: "alunos#adicionar_words", as: :adicionar_words
    patch "alterar_vigencia/:id", to: "alunos#alterar_vigencia", as: :alterar_vigencia
    post "enviar_correcao", to: "correcoes#enviar_correcao", as: :enviar_correcao
  end

  namespace :user do
    get "dashboard", to: "dashboard#index"
    get "dashboard/search", to: "dashboard#search", as: :dashboard_search

    get "redacoes", to: "redacoes#index"
    get "redacoes/search", to: "redacoes#search", as: :redacoes_search

    get "settings", to: "settings#index"
    get "explorar", to: "explorar#index"
    get "carrinho", to: "carrinho#index"
    get "pedidos", to: "pedidos#index"

    post "gerar_pedido", to: "pedidos#gerar"

    resources :cursos do
      member do
        get :player
      end
    end

    resources :words do
      member do
        get :proposta
        get :reload_redacao
        post :save_user_word_pdf
        post :concluir
      end

      resources :chats do
        resources :messages
      end
    end
  end

  resource :cart, only: [] do
    post "add/:curso_id", to: "cart#add", as: :add_to
    delete "remove/:curso_id", to: "cart#remove", as: :remove_from
  end

  resources :user_aulas
  resources :freights
  resources :cursos
  resources :videos
  resources :pedidos
  resources :temas, only: :show

  resources :notifications, only: [:index] do
    member do
      patch :marcar_leitura
    end
  end

  resources :favoritos, only: [:create] do
    delete ":tema_id", to: "favoritos#destroy", as: :remove, on: :collection
  end

  get "/success", to: "payments#success"
  get "/cancel", to: "payments#cancel"

  post "/create_checkout_session", to: "payments#create_checkout_session"
  post "calcular_frete", to: "freights#calcular_frete"
  post "importar_fretes", to: "freights#importar_fretes"
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  include StateMachines::PedidoState

  belongs_to :cart, class_name: "::Cart"
  belongs_to :user, class_name: "::User"

  before_validation :set_code, on: :create
  before_validation :set_cursos_ids, on: :create

  validate :value_total, if: -> { cart.total != total }

  after_save :confirmar_pedido

  attr_readonly :cart_id, :user_id

  scope :find_by_code, ->(code) {
    where("code ILIKE ?", "%#{code}%")
  }

  def liberar_cursos_redacoes
    cart.cursos.each do |curso|
      UserCurso.create(user_id: user_id, curso_id: curso.id, data_inicio: Time.zone.now, data_fim: Time.zone.now + curso.vigencia.months)
      Notification.create(user_id: user_id, title: "Novo curso disponível!", body: "#{curso.name.upcase} já está liberado na área do aluno", notification_type: "add_curso")

      curso.words.each do |word|
        UserWord.create(user_id: user_id, word_id: word.id, curso_id: curso.id)
        Notification.create(user_id: user_id, title: "Nova redação disponível!", body: "#{word.tema.upcase} já está liberado na área do aluno", notification_type: "add_word")
      end
    end
  end

  def confirmar_pedido
    confirmar
  end

  def set_code
    loop do
      self.code = SecureRandom.alphanumeric(8).upcase
      break unless Pedido.exists?(code: code)
    end
  end

  def set_cursos_ids
    self.cursos_ids = cart.cursos.pluck(:id)
  end

  private

  def value_total
    errors.add(:base, "Valores foram adulterados, porém já foram concertados")
    update(total: cart.total)
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [ :google_oauth2 ]

  has_one :cart, dependent: :destroy
  has_one_attached :imagem

  has_many :user_cursos, dependent: :destroy
  has_many :cursos, through: :user_cursos
  has_many :user_words, dependent: :destroy
  has_many :words, through: :user_words
  has_many :user_aulas, dependent: :destroy
  has_many :watched_aulas, through: :user_aulas, source: :aula
  has_many :pedidos, dependent: :destroy
  has_many :messages, as: :dono, class_name: "::Message"
  has_many :notifications, dependent: :destroy
  has_many :favoritos, dependent: :destroy

  validates :nome, :sobrenome, :cpf, presence: true
  validates :cpf, uniqueness: { case_sensitive: false }
  validates :cpf, format: { with: /\A\d{11}\z/, message: "deve conter 11 dígitos numéricos" }
  validate :cpf_must_be_valid

  def cpf_must_be_valid
    errors.add(:cpf, "não é válido") unless CPF.valid?(cpf)
  end

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data["email"]).first

    user ||= User.create(nome: data["name"],
                        email: data["email"],
                        password: Devise.friendly_token[0, 20])
    user
  end

  def set_admin
    update(admin: true)
  end

  def admin?
    return true if admin

    false
  end
end

app/controllers/admin/pedidos_controller.rb
class Admin::PedidosController < AdminsBackofficeController
  def index
    @pedidos = Pedido.order(updated_at: :desc)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminsBackofficeController
  def index
    @users = User.all
  end

  def toggle_active
    @user = User.find(params[:id])
    @user.update(active: !@user.active)

    redirect_to admin_users_path
  end
end

app/controllers/user/carrinho_controller.rb
class User::CarrinhoController < ApplicationController
  layout "user_dashboard"

  def index
    @cart = current_user.cart
    @cursos = @cart.cursos.order(value: :desc)
    @code = params[:code]
  end
end

app/controllers/user/chat_controller.rb
class User::ChatController < ApplicationController
  def show
    @chat = Chat.find(params[:id])
  end
end

app/controllers/user/cursos_controller.rb
class User::CursosController < ApplicationController
  layout "player"

  def player
    @user_curso = current_user.user_cursos
                              .ativos
                              .where(curso_id: params[:id])
                              .first

    @curso = current_user.cursos
                         .where(id: params[:id])
                         .first

    return redirect_to user_dashboard_path if @curso.blank? || @user_curso.blank?
    @modulos = @curso.modulos
  end
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  layout "user_dashboard"

  def index
    @user_cursos = current_user.user_cursos.order(progresso: :desc)
    @continuar_cursos = current_user.user_cursos.where(curso_id: current_user.user_aulas&.last.try(:curso_id))
  end
end

app/controllers/user/explorar_controller.rb
class User::ExplorarController < ApplicationController
  layout "user_dashboard"

  def index
    @all_cursos = Curso.all

    if params[:query].present?
      @all_cursos = Curso.find_by_name(params[:query])
    end

    if params[:prova].present?
      @all_cursos = Curso.find_by_prova(params[:prova])
    end
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  def create
    @chat = Chat.find(params[:chat_id])
    @message = @chat.messages.build(message_params)
    @message.dono = current_user

    @word = @chat.user_word.word

    if @message.save
      redirect_to proposta_user_word_path(@word)

      ::Notification.create!(
          user_id: current_user.id,
          painel: "admin", title: "Mensagem de #{current_user.nome}",
          body: "#{@message.content}", notification_type: "message",
          chat_id: @chat.id
      )
    else
      render "chat/show"
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/user/pedidos_controller.rb
class User::PedidosController < ApplicationController
  layout "user_dashboard"

  def index
    @user = current_user
    @pedidos = @user.pedidos.order(updated_at: :desc)
  end
end

app/controllers/user/redacoes_controller.rb
class User::RedacoesController < ApplicationController
  layout "user_dashboard"

  def index
    @user_words = current_user.user_words.limit(8)
  end

  def search
  end
end

app/controllers/user/settings_controller.rb
class User::SettingsController < ApplicationController
  layout "user_dashboard"

  def index
    @user = current_user
  end
end

app/controllers/user/words_controller.rb
class User::WordsController < ApplicationController
  layout "proposta"

  def proposta
    @word = Word.find(params[:id])
    @user_word = current_user.user_words.where(word_id: @word.id).first
    @user_curso = current_user.user_cursos.where(curso_id: @user_word.curso_id).first
    @chat = Chat.find_or_create_by!(
                    user_word_id: @user_word.id,
                  )
    @messages = @chat.messages
  end

  def save_user_word_pdf
    @word = Word.find(params[:id])
    @user_word = current_user.user_words.where(word_id: @word.id).first
    @duration_seconds = params[:duration_seconds]

    if params[:file].present?
      if @user_word.user_redacao.attach(params[:file])
        redirect_to proposta_user_word_path(@user_word.word_id), notice: "Redação enviada com sucesso."
      end
    else
      redirect_back fallback_location: root_path, alert: "Arquivo não selecionado."
    end
  end

  def concluir
    @word = Word.find(params[:id])
    @user_word = current_user.user_words.where(word_id: @word.id).first
    @user_word.update(concluido: true, data_conclusao: Time.zone.now)
    @user_word.enviar

    redirect_to proposta_user_word_path(@user_word.word_id), notice: "Redação enviada com sucesso."
  end

  def reload_redacao
    @user_word = current_user.user_words.find(params[:id])
    if @user_word.user_redacao.attached?
      render json: {
        url: url_for(@user_word.user_redacao),
        content_type: @user_word.user_redacao.content_type
      }
    else
      render json: { error: "Sem arquivo" }, status: :not_found
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token, only: [ :google_oauth2 ]

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", kind: "Google"
      sign_in_and_redirect @user, event: :authentication
    end
  end

  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :html
  layout "login"
  before_action :configure_sign_up_params, only: [ :create ]
  before_action :configure_account_update_params, only: [ :update ]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    request.format = :html

    @user = current_user

    if @user.update(user_params)
      redirect_to user_settings_path, notice: "Configurações atualizadas com sucesso!"
    else
      redirect_to user_settings_path, notice: "Erro!"
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  private

  def user_params
    params.require(:user).permit(:nome, :sobrenome, :imagem)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :nome, :sobrenome, :cpf ])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [ :nome, :sobrenome, :cpf ])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout "login"

  def after_sign_in_path_for(resource)
    root_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/pedidos/index.html.erb
<div class="mt-3" style="margin-left: 21px">
  <h5 href="/">
    <i class="bi bi-receipt fs-5" style="margin-right: 8px"></i>
    <span style="position: relative; top: -1px; font-size: 16px;">Meus Pedidos</span>
  </h5>
</div>

<div class="full-width-container d-flex" style="gap: 15px; margin-top: -10px">
  <div style="flex-direction: column; gap: 15px; width: 63%; white-space: nowrap; margin-left: 18px">
    <% if @pedidos.present? %>
      <% @pedidos.each_with_index do |pedido, index| %>
        <div class="card mt-3 shadow-sm border p-2">
          <div class="card-header d-flex justify-content-between align-items-center bg-white" style="cursor: pointer;" id="togglePedido<%= index %>">
            <div>
              <p class="m-0" style="font-size: 14px; font-weight: 500"><%= pedido.created_at.in_time_zone('America/Sao_Paulo').strftime('%d/%m/%Y %H:%M') %></p>
              <div class="d-flex">
                <i class="bi bi-check2-circle fs-5 text-success"></i>
                <strong class="text-success" style="font-size: 13px; margin-left: 6px; margin-top: 5px; font-weight: 600"><%= pedido.status.upcase == "FINALIZADO" ? "Finalizado" : "Pendente" %></strong>
              </div>
              <p class="m-0 mt-0" style="font-weight: 600; font-size: 13px;">Código: <%= pedido.code %></p>
              <p class="m-0 mt-1 mb-2 text-secondary" style="font-size: 12px">
                <%= pedido.cursos_count %> Cursos • Valor Total: <%= number_to_currency(pedido.total, unit: "R$", separator: ",", delimiter: ".", format: "%u %n") %>
              </p>
            </div>
            <i id="icon<%= index %>" class="bi bi-chevron-down fs-4 transition-rotate"></i>
          </div>

          <div id="pedidoDetalhes<%= index %>" class="collapse">
            <div class="card-body">

              <div style="width: 100%; gap: 10px; display: flex;">
                <% Curso.where(id: pedido.cursos_ids).each do |curso| %>
                  <div class="col align-items-center justify-content-center w-50" style="margin-top: 2px;">
                    <div class="container card shadow mb-2 rounded-4 w-100 p-2">
                      <a style="text-decoration: none; color: black">
                        <div class="row g-0">
                          <div class="col-md-4 d-flex align-items-center justify-content-center">
                            <% if curso.imagem.present? %>
                              <%= image_tag curso.imagem, class: "", alt: curso.name, style: "max-height: 100px; max-width: 100%; object-fit: contain;" %>
                            <% end %>
                          </div>
                          <div class="col-md-8">
                            <div class="card-body">
                              <h5 class="card-title" style="font-size: 13px; font-weight: 350; margin-bottom: 1px;"><%= curso.name %></h5>
                              <strong class="mb-3" style="font-size: 13px; font-weight: 600;" >R$ <%= number_with_precision(curso.value, precision: 2, separator: ",") %></strong>
                              <span class="preco-riscado">R$ <%= number_with_precision(curso.value_riscado, precision: 2, separator: ",") %></span>
                              <div class="d-flex mt-0">
                                <i class="bi bi-stopwatch text-danger" style="font-size: 11px; margin-top: 2px;"></i>
                                <strong class="text-danger" style="font-size: 10px; margin-left: 5px; margin-top: 4px; font-weight: 600">
                                  Expira em: <span class="countdown" data-expire="<%= current_user.user_cursos.where(curso_id: curso.id).first.data_fim.iso8601 %>">carregando...</span>
                                </strong>
                              </div>
                            </div>
                          </div>
                        </div>
                      </a>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <div class="d-flex mt-3" style="margin-left: 4px; font-size: 13px;">
        <i class="bi bi-exclamation-triangle text-danger" style="margin-left: 2px"></i>
        <p style="margin-left: 10px;" class="text-danger">Você ainda não tem nenhum pedido...</p>
      </div>
    <% end %>
  </div>

  <div style="flex-direction: column; gap: 15px; width: 31%; white-space: nowrap;">
    <div class="curso-info">
      <div class="curso-preview mt-4 text-dark">
        <div class="pagar-box text-dark">
          <h5 href="/">
            <i class="bi bi-wallet fs-6" style="margin-right: 5px"></i>
            <span style="position: relative; top: -2px; font-size: 13px">Finalize seu pedido</span>
          </h5>
          <div class="preco mt-3">
            <% @cursos.each do |curso| %>
              <div class="d-flex justify-content-between">
                <span class="preco-atual"><%= curso.name %></span>
                <span class="preco-antigo"><%= number_to_currency(curso.value, unit: "R$", separator: ",", delimiter: ".", format: "%u %n") %></span>
              </div>
            <% end %>
          </div>

          <hr>

          <div class="preco mt-3 d-flex justify-content-between">
            <span class="preco-atual">Valor Total</span>
            <span class="preco-antigo"><%= number_to_currency(@cart.total, unit: "R$", separator: ",", delimiter: ".", format: "%u %n") %></span>
          </div>

          <div style="width: 100%; margin-top: 20px">
            <%= form_with url: create_checkout_session_path, method: :post, local: true do %>
              <%= hidden_field_tag :cart_id, @cart.id %>
              <%= button_tag type: "submit", class: "btn-roxo btn-comprar p-2 d-flex align-items-center gap-2 justify-content-center", disabled: @cursos.blank? ? true : false do %>
                <i class="bi bi-credit-card-fill fs-5" style="margin-top: -2px;"></i>
                Cartão de Crédito/Débito
              <% end %>
            <% end %>
          </div>

          <button class="btn-dark btn-pix d-flex align-items-center mt-1 justify-content-center">
            <img src="https://cdn.simpleicons.org/pix/00B4AA" alt="Pix" height="20" style="margin-left: -7px; margin-right: 7px;">
            Gerar Pix QRCode
          </button>
        </div>
      </div>
    </div>
  </div>
</div>

<br>

<script>
  document.addEventListener('DOMContentLoaded', function () {
    document.querySelectorAll('[id^="togglePedido"]').forEach((header, index) => {
      const icon = document.getElementById(`icon${index}`);
      const target = document.getElementById(`pedidoDetalhes${index}`);

      header.addEventListener('click', function () {
        const bsCollapse = bootstrap.Collapse.getInstance(target) || new bootstrap.Collapse(target, { toggle: false });

        if (target.classList.contains('show')) {
          bsCollapse.hide();
          icon.style.transform = 'rotate(0deg)';
        } else {
          bsCollapse.show();
          icon.style.transform = 'rotate(180deg)';
        }
      });
    });
  });

  function startCountdown() {
    const countdownElems = document.querySelectorAll('.countdown');

    function updateCountdown() {
      const now = new Date();

      countdownElems.forEach(elem => {
        const expireDate = new Date(elem.getAttribute('data-expire'));
        let diff = expireDate - now;

        if (diff <= 0) {
          elem.textContent = 'Expirado';
          return;
        }

        const days = Math.floor(diff / (1000 * 60 * 60 * 24));
        diff -= days * (1000 * 60 * 60 * 24);
        const hours = Math.floor(diff / (1000 * 60 * 60));
        diff -= hours * (1000 * 60 * 60);
        const minutes = Math.floor(diff / (1000 * 60));
        diff -= minutes * (1000 * 60);
        const seconds = Math.floor(diff / 1000);

        elem.textContent = `${days}d ${hours}h ${minutes}min ${seconds}s`;
      });
    }

    updateCountdown();
    setInterval(updateCountdown, 1000);
  }

  document.addEventListener('DOMContentLoaded', startCountdown);

</script>