config/routes.rb
Rails.application.routes.draw do
  root to: "welcomes#index"

  get "/apresentacao", to: "welcomes#apresentacao"
  get "/acesso_livre", to: "welcomes#acesso_livre"
  get "/temas", to: "welcomes#temas"
  get "/cursos", to: "welcomes#cursos"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_for :admins, skip: [ :registrations ], path: "admin", controllers: { sessions: "admins/sessions" }, path_names: {
    sign_in: "login",
    sign_out: "logout"
  }

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    get "alunos", to: "alunos#index"
    get "pedidos", to: "pedidos#index"
    get "pagamento", to: "pagamento#index"
    get "correcoes", to: "correcoes#index"
    get "find_by_alunos", to: "correcoes#alunos"
    get "alunos/:id/notifications", to: "alunos#notifications", as: "aluno_notifications"
    get "chats/:id/messages", to: "chats#messages", as: :chat_messages

    resources :correcoes
    resources :temas
    resources :words

    resources :chats, only: [ :show ] do
      resources :messages, only: [ :create ]
    end

    resources :users do
      member do
        patch :toggle_active
      end
    end

    resources :cursos do
      collection do
        post :delete_multiple
        post :add_word
        post :remove_word
      end

      post :destroy_image, on: :member
    end

    post "adicionar_cursos", to: "alunos#adicionar_cursos", as: :adicionar_cursos
    post "adicionar_words", to: "alunos#adicionar_words", as: :adicionar_words
    patch "alterar_vigencia/:id", to: "alunos#alterar_vigencia", as: :alterar_vigencia
    post "enviar_correcao", to: "correcoes#enviar_correcao", as: :enviar_correcao
  end

  namespace :user do
    get "dashboard", to: "dashboard#index"
    get "dashboard/search", to: "dashboard#search", as: :dashboard_search

    get "redacoes", to: "redacoes#index"
    get "redacoes/search", to: "redacoes#search", as: :redacoes_search

    get "settings", to: "settings#index"
    get "explorar", to: "explorar#index"
    get "carrinho", to: "carrinho#index"
    get "pedidos", to: "pedidos#index"

    post "gerar_pedido", to: "pedidos#gerar"

    resources :cursos do
      member do
        get :player
      end
    end

    resources :words do
      member do
        get :proposta
        get :reload_redacao
        post :save_user_word_pdf
        post :concluir
      end

      resources :chats do
        resources :messages
      end
    end
  end

  resource :cart, only: [] do
    post "add/:curso_id", to: "cart#add", as: :add_to
    delete "remove/:curso_id", to: "cart#remove", as: :remove_from
  end

  resources :user_aulas
  resources :freights
  resources :cursos
  resources :videos
  resources :pedidos
  resources :temas, only: :show

  resources :notifications, only: [:index] do
    member do
      patch :marcar_leitura
    end
  end

  resources :favoritos, only: [:create] do
    delete ":tema_id", to: "favoritos#destroy", as: :remove, on: :collection
  end

  get "/success", to: "payments#success"
  get "/cancel", to: "payments#cancel"

  post "/create_checkout_session", to: "payments#create_checkout_session"
  post "calcular_frete", to: "freights#calcular_frete"
  post "importar_fretes", to: "freights#importar_fretes"
end

app/models/freight.rb
class Freight < ApplicationRecord
  belongs_to :address_origem, class_name: "::Address"
  belongs_to :address_destino, class_name: "::Address"

  with_options allow_nil: true, prefix: true do
    delegate :cidade, :estado, :rua, :bairro, :cep, to: :address_origem
    delegate :cidade, :estado, :rua, :bairro, :cep, to: :address_destino
  end
end

app/controllers/freights_controller.rb
class FreightsController < ApplicationController
  def index
    set_freights
    @address_origem ||= {}
    @address_destino ||= {}
  end

  def calcular_frete
    cep_origem = format_cep(params[:cep_origem])
    cep_destino = format_cep(params[:cep_destino])

    calculate_service = CalculateFreightService.new(cep_origem, cep_destino, params[:height], params[:width], params[:length], params[:weight], params[:service_type_id])
    search_cep_origem = SearchCepService.new(cep_origem)
    search_cep_destino = SearchCepService.new(cep_destino)

    @address_origem ||= search_cep_origem.call
    @address_destino ||= search_cep_destino.call
    @frete_calculado ||= calculate_service.call

    create_freight = CreateFreightJob.perform_now(@address_origem, @address_destino, @frete_calculado)

    if create_freight
      set_freights
      render :index
    end
  end

  private

  def set_freights
    @freights ||= Freight.all
                         .preload(:address_origem, :address_destino)
                         .limit(7)
                         .order(created_at: :desc)
  end

  def format_cep(cep)
    cep.to_s.strip.gsub("-", "")
  end
end

app/views/freights/_header_fields.html.erb
<%= form_with(url: calcular_frete_path, method: :post, local: true, class: "row g-3") do |form| %>
  <div class="d-flex justify-content-between align-items-center mb-1">
    <h3 class="mt-2 text-title">NOVO FRETE</h3>
    <div>
      <a href="/" class="btn btn-danger btn-lg">
        <i class="bi bi-trash-fill"></i>
      </a>
      <button type="submit" class="btn btn-success btn-lg">
        <i class="bi bi-calculator-fill"></i>
      </button>
    </div>
  </div>

  <% if @frete_calculado.present? %>
    <div class="alert alert-warning d-flex justify-content-between align-items-center mt-3 col-7">
      <img src="<%= @frete_calculado["company"]["picture"] %>" alt="Logo da transportadora" class="img-fluid" style="max-height: 50px; margin-left: 40px;"><br>

      <p class="mt-3" style="margin-right: 50px;">
        Serviço: <strong> <%= @frete_calculado["name"] %> </strong><br>
        Transportadora: <strong> <%= @frete_calculado["company"]["name"] %> </strong><br>
        Preço Final: <strong> <%= number_to_currency(@frete_calculado["custom_price"].to_f, unit: "R$", separator: ",") %> </strong> <br>
        Prazo de Entrega: <strong> <%= @frete_calculado["delivery_time"] %> dias </strong>
      </p>
    </div>

    <%# <div class="col-1"></div> %>

    <div class="alert d-flex justify-content-center align-items-center mt-3 col-5">
      <img src="<%= state_image_url(@address_origem[:state]) %>" alt="Estado Origem" class="img-fluid" style="max-height: 80px; margin-right: 20px;">

      <i class="bi bi-arrow-right fs-2"></i>

      <img src="<%= state_image_url(@address_destino[:state]) %>" alt="Estado Destino" class="img-fluid" style="max-height: 80px; margin-left: 20px;">
    </div>
  <% end %>

  <div class="col-md-12">
    <%= form.label :service_type_id, "Tipo de serviço", class: "form-label fw-light" %>
    <%= form.select :service_type_id, options_for_select([['PAC', 1], ['Sedex', 2], ['Outros', 3]], selected: params[:service_type_id]), {}, { class: "form-control form-control-sm select2", id: "service_type_select", required: true } %>
  </div>

  <div class="col-md-6">
    <%= form.label :cep_origem, "CEP de Origem", class: "form-label fw-light" %>
    <%= form.text_field :cep_origem, class: "form-control form-control-sm", placeholder: "Digite o CEP", required: true, value: params[:cep_origem] %>
  </div>

  <div class="col-md-6">
    <%= form.label :cep_destino, "CEP de Destino", class: "form-label fw-light" %>
    <%= form.text_field :cep_destino, class: "form-control form-control-sm", placeholder: "Digite o CEP", required: true, value: params[:cep_destino] %>
  </div>

  <div class="col-md-4">
    <%= form.label :street_origem, "Rua", class: "form-label fw-light" %>
    <%= form.text_field :street_origem, class: "form-control form-control-sm", disabled: true, value: @address_origem[:street] %>
  </div>

  <div class="col-md-2">
    <%= form.label :bairro_origem, "Bairro", class: "form-label fw-light" %>
    <%= form.text_field :bairro_origem, class: "form-control form-control-sm", disabled: true, value: @address_origem[:bairro] %>
  </div>

  <div class="col-md-4">
    <%= form.label :street_destino, "Rua", class: "form-label fw-light" %>
    <%= form.text_field :street_destino, class: "form-control form-control-sm", disabled: true, value: @address_destino[:street] %>
  </div>

  <div class="col-md-2">
    <%= form.label :bairro_destino, "Bairro", class: "form-label fw-light" %>
    <%= form.text_field :bairro_destino, class: "form-control form-control-sm", disabled: true, value: @address_destino[:bairro] %>
  </div>

    <div class="col-md-3">
    <%= form.label :city_origem, "Cidade", class: "form-label fw-light" %>
    <%= form.text_field :city_origem, class: "form-control form-control-sm", disabled: true, value: @address_origem[:city] %>
  </div>

  <div class="col-md-3">
    <%= form.label :state_origem, "Estado", class: "form-label fw-light" %>
    <%= form.text_field :state_origem, class: "form-control form-control-sm", disabled: true, value: @address_origem[:state] %>
  </div>

  <div class="col-md-3">
    <%= form.label :city_destino, "Cidade", class: "form-label fw-light" %>
    <%= form.text_field :city_destino, class: "form-control form-control-sm", disabled: true, value: @address_destino[:city] %>
  </div>

  <div class="col-md-3 mb-3">
    <%= form.label :state_destino, "Estado", class: "form-label fw-light" %>
    <%= form.text_field :state_destino, class: "form-control form-control-sm", disabled: true, value: @address_destino[:state] %>
  </div>

  <hr>

  <div class="col-md-3">
    <%= form.label :weight, "Peso (kg)", class: "form-label fw-light" %>
    <%= form.number_field :weight, class: "form-control form-control-sm", required: true, value: params[:weight] %>
  </div>

  <div class="col-md-3">
    <%= form.label :length, "Comprimento (cm)", class: "form-label fw-light" %>
    <%= form.number_field :length, class: "form-control form-control-sm", required: true, value: params[:length] %>
  </div>

  <div class="col-md-3">
    <%= form.label :width, "Largura (cm)", class: "form-label fw-light" %>
    <%= form.number_field :width, class: "form-control form-control-sm", required: true, value: params[:width] %>
  </div>

  <div class="col-md-3">
    <%= form.label :height, "Altura (cm)", class: "form-label fw-light" %>
    <%= form.number_field :height, class: "form-control form-control-sm", required: true, value: params[:height] %>
  </div>
<% end %>

<script>
  $(document).ready(function() {
    $('#service_type_select').select2({
      theme: 'bootstrap4',
      placeholder: "Selecione o tipo de serviço",
      allowClear: true
    });
  });
</script>

app/views/freights/_import_freights.html.erb
<%= form_with(url: importar_fretes_path, method: :post, local: true, multipart: true) do |form| %>
  <div class="d-flex justify-content-between align-items-center mb-1">
    <h3 class="mt-2 text-title">Importação de Fretes</h3>
    <div class="row">
      <%= form.file_field :file_pdf, required: true %>
    </div>
    <button type="submit" class="btn btn-success btn-lg">
      <i class="bi bi-upload"></i> Enviar
    </button>
  </div>
<% end %>

app/views/freights/_list_freights.erb
<div class="d-flex justify-content-between align-items-center mb-1">
  <h3 class="mt-2 text-title">FRETES</h3>
</div>

<% if @freights.present? %>
  <table class="table table-bordered mt-3">
    <thead class="thead-dark">
      <tr class="table-secondary">
        <th>Serviço</th>
        <th>Companhia</th>
        <th>Origem</th>
        <th>Destino</th>
        <th>Prazo</th>
        <th>Preço</th>
        <th class="text-right">Data da requisição</th>
      </tr>
    </thead>
    <% @freights.each do |frete| %>
      <tbody>
        <tr>
          <td><%= frete.nome_do_serviço %></td>
          <td><%= frete.compania %></td>
          <td><%= frete.address_origem_cidade %> - <%= frete.address_origem_estado %></td>
          <td><%= frete.address_destino_cidade %> - <%= frete.address_destino_estado %></td>
          <td><%= frete.tempo_estimado ? "#{frete.tempo_estimado} Dias" : " - " %></td>
          <td><%= frete.preço_final ? "R$ #{frete.preço_final}".gsub('.', ',') : " - "  %></td>
          <td><%= frete.created_at.in_time_zone('America/Sao_Paulo').strftime('%d/%m/%Y %H:%M:%S') %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
<% else %>
  <p class="text-center">Nenhum frete disponível.</p>
<% end %>

app/views/freights/index.html.erb
<div class="container mt-3 fixed-container">
  <div class="card-freight shadow p-5 fixed-card">
    <%= render partial: 'list_freights'%>
    <br>
    <%= render partial: 'header_fields' %>
  </div>
</div>