config/routes.rb
Rails.application.routes.draw do
  root to: "welcomes#index"

  get "/apresentacao", to: "welcomes#apresentacao"
  get "/acesso_livre", to: "welcomes#acesso_livre"
  get "/temas", to: "welcomes#temas"
  get "/cursos", to: "welcomes#cursos"

  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  devise_for :admins, skip: [ :registrations ], path: "admin", controllers: { sessions: "admins/sessions" }, path_names: {
    sign_in: "login",
    sign_out: "logout"
  }

  namespace :admin do
    get "dashboard", to: "dashboard#index"
    get "alunos", to: "alunos#index"
    get "pedidos", to: "pedidos#index"
    get "pagamento", to: "pagamento#index"
    get "correcoes", to: "correcoes#index"
    get "find_by_alunos", to: "correcoes#alunos"
    get "alunos/:id/notifications", to: "alunos#notifications", as: "aluno_notifications"
    get "chats/:id/messages", to: "chats#messages", as: :chat_messages

    resources :correcoes
    resources :temas
    resources :words

    resources :chats, only: [ :show ] do
      resources :messages, only: [ :create ]
    end

    resources :users do
      member do
        patch :toggle_active
      end
    end

    resources :cursos do
      collection do
        post :delete_multiple
        post :add_word
        post :remove_word
      end

      post :destroy_image, on: :member
    end

    post "adicionar_cursos", to: "alunos#adicionar_cursos", as: :adicionar_cursos
    post "adicionar_words", to: "alunos#adicionar_words", as: :adicionar_words
    patch "alterar_vigencia/:id", to: "alunos#alterar_vigencia", as: :alterar_vigencia
    post "enviar_correcao", to: "correcoes#enviar_correcao", as: :enviar_correcao
  end

  namespace :user do
    get "dashboard", to: "dashboard#index"
    get "dashboard/search", to: "dashboard#search", as: :dashboard_search

    get "redacoes", to: "redacoes#index"
    get "redacoes/search", to: "redacoes#search", as: :redacoes_search

    get "settings", to: "settings#index"
    get "explorar", to: "explorar#index"
    get "carrinho", to: "carrinho#index"
    get "pedidos", to: "pedidos#index"

    post "gerar_pedido", to: "pedidos#gerar"

    resources :cursos do
      member do
        get :player
      end
    end

    resources :words do
      member do
        get :proposta
        get :reload_redacao
        post :save_user_word_pdf
        post :concluir
      end

      resources :chats do
        resources :messages
      end
    end
  end

  resource :cart, only: [] do
    post "add/:curso_id", to: "cart#add", as: :add_to
    delete "remove/:curso_id", to: "cart#remove", as: :remove_from
  end

  resources :user_aulas
  resources :freights
  resources :cursos
  resources :videos
  resources :pedidos
  resources :temas, only: :show

  resources :notifications, only: [:index] do
    member do
      patch :marcar_leitura
    end
  end

  resources :favoritos, only: [:create] do
    delete ":tema_id", to: "favoritos#destroy", as: :remove, on: :collection
  end

  get "/success", to: "payments#success"
  get "/cancel", to: "payments#cancel"

  post "/create_checkout_session", to: "payments#create_checkout_session"
  post "calcular_frete", to: "freights#calcular_frete"
  post "importar_fretes", to: "freights#importar_fretes"
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  layout "welcome"
  skip_before_action :authenticate_user!, only: %i[index apresentacao acesso_livre temas cursos]

  def index
    set_cursos
  end

  def apresentacao
    @title_page = "Quem somos"
  end

  def acesso_livre
    @title_page = "Acesso Livre"
  end

  def temas
    @title_page = "Temas de Redação"
    @temas_collection = ::Tema.all

    if params[:prova].present?
      @temas_collection = ::Tema.find_by_prova(params[:prova])
    end

    if current_user
      @favoritos_ids = current_user.favoritos.pluck(:tema_id)
    else
      @favoritos_ids = []
    end
  end

  def cursos
    @title_page = "Cursos"
    @cursos_collection = ::Curso.all

    if params[:prova].present?
      @cursos_collection = ::Curso.find_by_prova(params[:prova])
    end
  end

  private

  def set_cursos
    @cursos ||= Curso.all.limit(5)
  end
end

app/views/welcomes/_alunos_aprovados.html.erb
<div class="container py-1">
  <div class="mb-1 ms-4 d-flex" style="width: 93%;">
    <i class="bi bi-mortarboard fs-5 icon-mobile-size margin-top-mobile-icon" style="margin-top: -5px; margin-right: 9px; margin-left: 10px;"></i>
    <h2 class="ms-2 mobile-text-title" style="font-size: 19px; font-weight: 400;">Alunos aprovados</h2>
  </div>

  <hr class="text-dark mobile-none" style="width: 95.6%; margin-left: 30px; margin-bottom: 15px; margin-top: -7px; opacity: 10%;">

  <div class="row d-flex ms-3 alunos-aprovados-card-mobile" style="width: 97.7%;">
    <div class="col-md-2">
      <div class="text-center shadow hover-medium">
        <img src="/images/lais-aprovada.png" alt="Laís aprovada"
            class="shadow-sm"
            style="width: 166px; height: 140px; object-fit: cover;">
        <div class="mt-1">
          <strong style="font-size: 14px;">Laís</strong><br>
          <small style="font-size: 13px;" class="text-muted">Direito - UFMG</small>
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <div class="text-center shadow hover-medium">
        <img src="/images/aluna_2.png" alt="João aprovado"
            class="shadow-sm"
            style="width: 166px; height: 140px; object-fit: cover;">
        <div class="mt-1">
          <strong style="font-size: 14px;">Daniele</strong><br>
          <small style="font-size: 13px;" class="text-muted">Ciên. de Computação - USP</small>
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <div class="text-center shadow hover-medium">
        <img src="/images/aluna_3.png" alt="João aprovado"
            class="shadow-sm"
            style="width: 166px; height: 140px; object-fit: cover;">
        <div class="mt-1">
          <strong style="font-size: 14px;">Luana</strong><br>
          <small style="font-size: 13px;" class="text-muted">Medicina - USP</small>
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <div class="text-center shadow hover-medium">
        <img src="/images/aluna_5.png" alt="João aprovado"
            class="shadow-sm"
            style="width: 166px; height: 140px; object-fit: cover;">
        <div class="mt-1">
          <strong style="font-size: 14px;">Júlia</strong><br>
          <small style="font-size: 13px;" class="text-muted">Medicina - UAM</small>
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <div class="text-center shadow hover-medium">
        <img src="/images/aluna_6.png" alt="João aprovado"
            class="shadow-sm"
            style="width: 166px; height: 140px; object-fit: cover;">
        <div class="mt-1">
          <strong style="font-size: 14px;">Maria Beatriz</strong><br>
          <small style="font-size: 13px;" class="text-muted">Enfermagem - USP</small>
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <div class="text-center shadow hover-medium">
        <img src="/images/aluna_4_carol.png" alt="João aprovado"
            class="shadow-sm"
            style="width: 166px; height: 140px; object-fit: cover;">
        <div class="mt-1">
          <strong style="font-size: 14px;">Carol</strong><br>
          <small style="font-size: 13px;" class="text-muted">Medicina - USP</small>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcomes/_carrosel.html.erb
<div class="carousel-section">
  <div class="carousel-wrapper">
    <button class="carousel-btn prev">&#10094;</button>
    <div class="carousel-container">
      <div class="carousel-track shadow">
        <% 3.times.each do |item| %>
          <div class="carousel-slide">
            <img class="carousel-image" src="/images/banner-civic.png" alt="Login image" />
          </div>
        <% end %>
      </div>
    </div>
    <button class="carousel-btn next">&#10095;</button>
  </div>
</div>

app/views/welcomes/_provas_anteriores.html.erb
<div class="container mb-5" style="margin-top: 5px;">
  <div class="mt-2 ms-4 d-flex title-prova-anteriores-mobile" style="width: 93%;">
    <i class="bi bi-chevron-double-left icon-mobile-size fs-6" style="margin-top: -1px; margin-right: 6px; margin-left: 10px;"></i>
    <h2 class="ms-2 mobile-text-title" style="font-size: 18px; font-weight: 400;">
      Provas anteriores
    </h2>
  </div>

  <hr class="text-dark mobile-none" style="width: 95.6%; margin-left: 30px; margin-bottom: 15px; margin-top: -3px; opacity: 10%;">

  <div class="row gx-3 prova-anteriores-card-mobile margin-top-mobile-minimun" style="margin-left: 25px; margin-right: 0; width: 97%;">
    <!-- CARD FUNCIONAL COM VÍDEO -->
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 d-flex mb-3">
      <div class="redacoes-card d-flex flex-column align-items-center text-dark w-100 text-decoration-none"
            id="video-card"
            style="cursor: pointer;">
        <div class="position-relative w-100 bg-dark d-flex justify-content-center align-items-center"
              style="border-radius: 10px; height: 350px;" id="video-card-content">
          <p class="text-white m-0 fs-4" style="opacity: 80%">2021</p>
        </div>
      </div>
    </div>

    <!-- Outros cards (sem funcionalidade ainda) -->
    <% 3.times.each_with_index do |item, index| %>
      <div class="col-12 col-sm-6 col-md-4 col-lg-3 d-flex mb-3">
        <a href="#" class="redacoes-card d-flex flex-column align-items-center text-dark w-100 text-decoration-none">
          <div class="position-relative w-100 bg-dark d-flex justify-content-center align-items-center"
                style="border-radius: 10px; height: 350px;">
            <p class="text-white m-0 fs-4" style="opacity: 80%">202<%= index + 2 %></p>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>


<script>
  document.addEventListener("DOMContentLoaded", function () {
    const card = document.getElementById("video-card");
    const content = document.getElementById("video-card-content");

    card.addEventListener("click", function () {
      const video = document.createElement("video");

      video.src = "/videos/videoplayback.mp4"; // coloque o vídeo em public/videos/
      video.controls = true;
      video.autoplay = true;
      video.playsInline = true;
      video.controlsList = "nodownload noplaybackrate";
      video.style.width = "100%";
      video.style.height = "100%";
      video.style.objectFit = "cover";
      video.style.borderRadius = "10px";
      video.setAttribute("class", "shadow-sm");

      content.innerHTML = "";
      content.appendChild(video);
    });
  });
</script>

app/views/welcomes/_vestibulares.html.erb
<div class="vestibulares margin-top-mobile-medium">
  <div class="vestibular">
    <div class="vestibular-card" data-prova-nome="unicamp">
      <a href="/cursos?prova=unicamp" class="text-dark" style="text-decoration: none;">
        <img src="/images/unicamp.jpg" alt="Login image" />
      </a>
    </div>
    <div class="vestibular-card" data-prova-nome="enem">
      <a href="/cursos?prova=enem" class="text-dark" style="text-decoration: none;">
        <img src="/images/enem-branco.jpg" alt="Login image" />
      </a>
    </div>
    <div class="vestibular-card" data-prova-nome="unesp">
      <a href="/cursos?prova=unesp" class="text-dark" style="text-decoration: none;">
        <img src="/images/unesp.jpg" alt="Login image" />
      </a>
    </div>
    <div class="vestibular-card" data-prova-nome="usp">
      <a href="/cursos?prova=usp" class="text-dark" style="text-decoration: none;">
        <img src="/images/usp.jpg" alt="Login image" />
      </a>
    </div>
  </div>
  <hr>
</div>

app/views/welcomes/acesso_livre.html.erb
<div class="container mb-5 flex-wrap justify-content-center margin-top-mobile-medium card-acesso-livre-mobile" style="margin-top: -25px; width: 1240px;">
  <div class="w-100 d-flex" style="margin-left: 38px">
    <div class="insta-wrapper shadow" style="margin-left: -8px">
      <div class="insta-loader"></div>
      <blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/reel/DHY5FXbp2YM/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" data-instgrm-version="14"></blockquote>
    </div>

    <div class="insta-wrapper shadow">
      <div class="insta-loader"></div>
      <blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/reel/DHybX1Ss5L6/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" data-instgrm-version="14"></blockquote>
    </div>

    <div class="insta-wrapper shadow">
      <div class="insta-loader"></div>
      <blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/reel/DHOQ_SNMx-n/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" data-instgrm-version="14"></blockquote>
    </div>
  </div>
</div>

<div class="container mb-5 flex-wrap justify-content-center" style="margin-top: -50px; width: 1240px;">
  <div class="w-100 d-flex" style="margin-left: 38px">
    <div class="insta-wrapper shadow" style="margin-left: -8px">
      <div class="insta-loader"></div>
      <blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/reel/DHHitvXs0aO/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==" data-instgrm-version="14"></blockquote>
    </div>

    <div class="insta-wrapper shadow">
    </div>

    <div class="insta-wrapper shadow">
    </div>
  </div>
</div>

<div class="margin-top-mobile-max-extra">
  <%= render 'vestibulares' %>
</div>

<%= render 'alunos_aprovados' %>

<script async src="//www.instagram.com/embed.js"></script>
<script>
  document.addEventListener("DOMContentLoaded", function () {
    const wrappers = document.querySelectorAll('.insta-wrapper');

    wrappers.forEach(wrapper => {
      const observer = new MutationObserver(() => {
        const iframe = wrapper.querySelector('iframe');
        if (iframe) {
          setTimeout(() => {
            wrapper.querySelector('.insta-loader')?.remove();
          }, 4000);

          observer.disconnect();
        }
      });

      observer.observe(wrapper, {
        childList: true,
        subtree: true
      });
    });
  });
</script>

app/views/welcomes/cursos.html.erb
<div style="margin-top: -15px;">
  <%= render 'vestibulares' %>

  <div class="container">
    <div class="mb-3 ms-4 d-flex margin-top-mobile-max-extra" style="width: 93%;">
      <i class="bi bi-play-btn icon-mobile-size margin-left-mobile-icon fs-5" style="margin-top: -3px; margin-right: 6px; margin-left: 10px;"></i>
      <h2 class="ms-2 mobile-text-title" style="font-size: 19px; font-weight: 400;">Cursos</h2>
    </div>

    <hr class="text-dark mobile-none" style="width: 95.6%; margin-left: 30px; margin-bottom: 13px; margin-top: -19px; opacity: 10%;">
  </div>

  <div class="container flex-columns-mobile mb-4">
    <div class="row row-cols-1 row-cols-md-2 g-0">
      <% @cursos_collection.each do |curso| %>
        <div class="col" style="margin-right: -15px;" data-prova-nome="<%= curso.prova %>">
          <div class="card shadow ms-4 hover p-2 card-mobile" style="width: 96.3%; height: 90%;">
            <a href="/cursos/<%= curso.id %>/edit" style="text-decoration: none; color: black">
              <div class="row g-0">
                <div class="col-md-3 ms-2 d-flex align-items-center justify-content-center">
                  <% if curso.imagem.present? %>
                    <%= image_tag curso.imagem, class: "mobile-imagem", alt: curso.name, style: "max-height: 120px; min-width: 100%; object-fit: cover; margin-bottom: 15px; border-radius: 5px;" %>
                  <% end %>
                </div>
                <div class="col-md-8 ms-1">
                  <div class="card-body mobile-card-body">
                    <h5 class="card-title font-mobile-small" style="font-size: 14px; font-weight: 350"><%= curso.name %></h5>
                    <div class="d-flex" style="margin-top: -7px;">
                      <strong class="font-mobile-small" style="font-size: 14px; font-weight: 600;" >R$ 10,00</strong>
                      <span class="font-mobile-small mobile-none" style="font-size: 12px; font-weight: 500; margin-left: 5px; margin-top: 2px; color: #888;"><%= curso.qtd_parcelas %>x sem juros</span>
                    </div>
                    <div class="d-flex" style="margin-top: -5px;">
                      <strong class="font-mobile-small" style="font-size: 14px; font-weight: 600;" >R$ <%= number_with_precision(curso.value, precision: 2, separator: ",") %></strong>
                      <span class="preco-riscado font-mobile-small mobile-none" style="font-size: 13px; margin-top: 1px;">R$ <%= number_with_precision(curso.value_riscado, precision: 2, separator: ",") %></span>
                    </div>

                    <div class="row mt-2 mobile-none">
                      <% if curso.grid_counter_words %>
                        <div class="col-12 col-md-5 mb-2">
                          <div class="item d-flex align-items-center">
                            <i class="bi bi-book me-1" style="font-size: 13px; margin-top: 2px;"></i>
                            <span style="font-size: 10px;"><%= curso.words.count %> redações disponíveis</span>
                          </div>
                        </div>
                      <% end %>

                      <% if curso.grid_mobile_and_tv %>
                        <div class="col-12 col-md-7 mb-2">
                          <div class="item d-flex align-items-center">
                            <i class="bi bi-phone" style="font-size: 13px; margin-top: 2px; margin-right: 2px;"></i>
                            <span style="font-size: 10px;">Acesso no dispositivo móvel e na TV</span>
                          </div>
                        </div>
                      <% end %>
                    </div>


                    <% if current_user.present? %>
                      <% if current_user.cart.cart_cursos.where(curso_id: curso.id).present? %>
                        <%= button_tag class: "btn text-success p-1 position-absolute hover d-flex", style: "top: 10px; right: 10px;  border: none;" do %>
                          <i class="bi bi-cart-check fs-6"></i>
                          <span style="font-size: 11px; margin-top: 4px; margin-left: 1px;">Adicionado</span>
                        <% end %>
                      <% elsif current_user.user_cursos.where(curso_id: curso.id).present? %>
                        <%= button_tag class: "btn text-success p-1 position-absolute d-flex mobile-none", style: "top: 10px; right: 10px;  border: none;" do %>
                          <span style="font-size: 11px; margin-top: 8px; margin-left: 3px;">
                            <i class="bi bi-check-circle-fill" style="font-size: 10px;"></i>
                            Adquirido: <%= current_user.user_cursos.where(curso_id: curso.id).first.data_inicio.in_time_zone('America/Sao_Paulo').strftime('%d/%m/%Y') %><br>
                            <span style="font-size: 11px; margin-left: 0px;" class="text-danger">
                            <i class="bi bi-exclamation-circle-fill" style="font-size: 10px;"></i>
                            Expira em: <%= current_user.user_cursos.where(curso_id: curso.id).first.data_fim.in_time_zone('America/Sao_Paulo').strftime('%d/%m/%Y') %></span>
                          </span>
                        <% end %>
                      <% else %>
                        <%= form_with url: add_to_cart_path(curso), method: :post, local: true do %>
                          <%= button_tag type: "submit", class: "btn text-dark p-1 position-absolute hover d-flex", style: "top: 10px; right: 10px; border: none;", onclick: "showLoadingAndRedirect()" do %>
                            <i class="bi bi-cart-plus fs-6"></i>
                            <span style="font-size: 11px; margin-top: 4px; margin-left: 1px;">Adicionar</span>
                          <% end %>
                        <% end %>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="margin-top-mobile-max-extra-extra">
    <%= render partial: 'provas_anteriores' %>
  </div>
</div>

<br><br>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const urlParams = new URLSearchParams(window.location.search);
    const provaParam = urlParams.get('prova');

    if (provaParam) {
      const vestibularCards = document.querySelectorAll('.vestibular-card');

      vestibularCards.forEach((card) => {
        const cardProva = card.dataset.provaNome?.toLowerCase();
        if (cardProva === provaParam.toLowerCase()) {
          card.classList.add('highlighted');
        }
      });
    }
  });
</script>

app/views/welcomes/index.html.erb
<div class="container mt-3 margin-top-mobile-min">
  <%= render 'carrosel' %>
</div>

<div class="margin-top-negative" style="margin-top: 30px;">
  <%= render 'vestibulares' %>
</div>

<div class="margin-top-mobile-max-extra" style="margin-top: 5px;">
  <%= render 'alunos_aprovados' %>
</div>

<div class="margin-top-mobile-max-extra-extra" style="margin-top: 35px;">
  <%= render partial: '/welcomes/provas_anteriores' %>
</div>

<script>
  document.addEventListener('DOMContentLoaded', () => {
    const track = document.querySelector('.carousel-track');
    const slides = document.querySelectorAll('.carousel-slide');
    const prevBtn = document.querySelector('.carousel-btn.prev');
    const nextBtn = document.querySelector('.carousel-btn.next');

    let index = 0;

    function updateCarousel() {
      track.style.transform = `translateX(-${index * 101}%)`;
    }

    nextBtn.addEventListener('click', () => {
      index = (index + 1) % slides.length; // volta pro início quando chegar no fim
      updateCarousel();
    });

    prevBtn.addEventListener('click', () => {
      index = (index - 1 + slides.length) % slides.length; // vai pro último se voltar no início
      updateCarousel();
    });
  });
</script>

app/views/welcomes/temas.html.erb
<div style="margin-top: -15px;">
  <div class="vestibulares margin-top-mobile-medium">
    <div class="vestibular">
      <div class="vestibular-card" data-prova-nome="unicamp">
        <a href="/temas?prova=unicamp" class="text-dark" style="text-decoration: none;">
          <img src="/images/unicamp.jpg" alt="Login image" />
        </a>
      </div>
      <div class="vestibular-card" data-prova-nome="enem">
        <a href="/temas?prova=enem" class="text-dark" style="text-decoration: none;">
          <img src="/images/enem-branco.jpg" alt="Login image" />
        </a>
      </div>
      <div class="vestibular-card" data-prova-nome="unesp">
        <a href="/temas?prova=unesp" class="text-dark" style="text-decoration: none;">
          <img src="/images/unesp.jpg" alt="Login image" />
        </a>
      </div>
      <div class="vestibular-card" data-prova-nome="usp">
        <a href="/temas?prova=usp" class="text-dark" style="text-decoration: none;">
          <img src="/images/usp.jpg" alt="Login image" />
        </a>
      </div>
    </div>
    <hr>
  </div>

  <br>

  <div class="container">
    <div class="mb-3 ms-4 d-flex margin-top-mobile-max title-redacao-mobile" style="width: 93%; margin-top: -20px;">
      <i class="bi bi-book-half fs-5 icon-mobile-size margin-top-mobile-icon" style="margin-top: -5px; margin-right: 6px; margin-left: 10px;"></i>
      <h2 class="ms-2 mobile-text-title" style="font-size: 16px; font-weight: 400;">Temas de Redação</h2>
    </div>

    <hr class="text-dark mobile-none" style="width: 95.6%; margin-left: 30px; margin-bottom: 10px; margin-top: -19px; opacity: 10%;">

    <div class="row gx-3 tema-card-mobile" style="margin-left: 25px; margin-right: 0; width: 97%;">
      <% @temas_collection.each do |tema| %>
        <div class="col-12 col-sm-6 col-md-4 col-lg-3 d-flex mb-3">
          <a href="/temas/<%= tema.id %>" class="redacoes-card d-flex flex-column align-items-center text-dark w-100" style="text-decoration: none;">
            <div class="meus-cursos-img position-relative w-100" style="border-radius: 10px;">
              <% if tema.capa.attached? %>
                <%= image_tag tema.capa, style: "max-height: 170px; width: 100%; object-fit: cover; border-radius: 10px 10px 0 0;" %>
                <% if current_user.present? %>
                  <% if @favoritos_ids.include?(tema.id) %>
                    <%= button_to remove_favoritos_path(tema_id: tema.id),
                                  method: :delete,
                                  class: "btn p-1 position-absolute top-0 end-0 m-2 favorite-button",
                                  style: "border: none;" do %>
                      <i class="bi bi-heart-fill text-danger fs-4" style="box-shadow: 0 4px 12px rgba(0, 0, 0, 0.05);"></i>
                    <% end %>
                  <% else %>
                    <%= button_to favoritos_path(tema_id: tema.id),
                                  method: :post,
                                  class: "btn p-1 position-absolute top-0 end-0 m-2 favorite-button",
                                  style: "border: none;" do %>
                      <i class="bi bi-heart-fill fs-4" style="color: #b6b6b6ff;"></i>
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
            </div>

            <div class="w-100" style="padding: 10px; box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3); border-radius: 0 0 10px 10px; min-height: 50px;">
              <h6 class="text-dark mb-0" style="font-size: 14px;"><strong style="font-size: 12px; margin-right: 1px; font-weight: 679"><%= tema.prova.upcase %></strong> <%= tema.name %></h6>
            </div>
          </a>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function () {
    const urlParams = new URLSearchParams(window.location.search);
    const provaParam = urlParams.get('prova');

    if (provaParam) {
      const vestibularCards = document.querySelectorAll('.vestibular-card');

      vestibularCards.forEach((card) => {
        const cardProva = card.dataset.provaNome?.toLowerCase();
        if (cardProva === provaParam.toLowerCase()) {
          card.classList.add('highlighted');
        }
      });
    }
  });
</script>